name = "StructuredCompositeOpt"
uuid = "d9bbf7bc-fdaa-4477-a432-ffa81b30db87"
authors = ["Gilles Bareilles <gilles.bareilles@protonmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
